# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cu6yeCPIawgCgRC8NsLJ4HyKBoZZsLAE
"""

def my_function():
    print("Hello From My Function!")

def my_function_with_args(username, greeting):
    print(f"Hello, {username} , From My Function!, I wish you {greeting}")

def sum_two_numbers(a, b):
    x= a + b
    return x

# print(a simple greeting)
my_function()

#prints - "Hello, John Doe, From My Function!, I wish you a great year!"
my_function_with_args("Carlos", "have a great year Violet!")

# after this line x will hold the value 3!
x = sum_two_numbers(1,2)
print(x)

def years(A):
    B = 2020
    C = B - A  
    print(f"The age of this person is : {C}")

A = int(input("What is your born year: "))

years(1900)

adduser (name  )

def erangaf(A):
    B = 2020
    C = B - int(A)
    print(f"The age of this person is : {C}")

A = input("What is your born year: ")

erangaf(1800)





sum_two_numbers(5,5)

list = ["yes","no"]
aswer = ""
aswer = input("do you want break?")
while aswer not in list:
      aswer = input("Please aswer : yes or no")
      if aswer == "yes":
          print("ok lest go!!")
      elif aswer =="no":
          print("ok more class!..")